name: AwesomeLib
version: '${project.version}'
main: org.supernederen.awesomelib.AwesomeLib
api-version: 1.19
authors: [ Champen_V1ldtand ]
description: A Library plugin for spigot plugin development
website: https://github.com/SuperNederen/AwesomeLib

permissions:
  awesomelib.command.*:
    description: Gives access to all AwesomeLib commands
    default: op
    children:
      awesomelib.command.awesomelib:
        value: true

commands:
    awesomelib:
      description: AwesomeLib command
      aliases: [al, awesome, awesomecommand, awecmd]
      permission: awesomelib.command.awesomelib
      permission-message: You do not have permission to use this command